### ISSUE TITLE
Similar idea

### ISSUE THREAD

**Issue by djui** [extend/sheriff#17]
Hej, 

this is not an issue, but I couldn't find another communication channel.

I implemented the same idea with a different approach a while back. Maybe you wanna have a look: https://github.com/djui/tulib/blob/master/src/tulib_types.erl

**Comment by essen** [comment]
Hello!

Here is fine, though you can also find us on IRC #erlounge and #erlang on freenode.

Didn't know there was already something (at least I think there wasn't any last year). I thought about basing it on Dialyzer and erl_types similar to what you did but didn't want the debug infos. The only other solution was parsing the source files (which Dialyzer also does).

Apparently we forgot a number of types you got, I'll work on adding them later. :)

**Comment by djui** [comment]
Cool. That function type will be tricky. I didn't find a way to type check the function arguments and/or return value types, though.

**Comment by essen** [comment]
Don't think you can without executing it, so I just check the arity myself.

**Comment by essen** [comment]
Thanks for the feedback, closing this.
