### ISSUE TITLE
Records with untyped fields leads to compilation fail.

### ISSUE THREAD

**Issue by define-null** [extend/sheriff#19]
Hello, I found a bug or a limitation while trying to compile my code, using shereff, which could be reduced to this simple example:

<pre>
-module(test).
-compile({parse_transform, sheriff}).
-export([wow/1]).

-record(watch, {filename :: string()}).
-type iwatch() :: #watch{}.

-record(state, {watches}).
-type istate() :: #state{}.

-spec wow(istate()) -> ok.
wow(State) ->
    ok.
</pre>

Althought I don't use any of sheriff functions here, compilation will stop with 
src/test.erl:299: function 'sheriff_$_record_$_state'/1 undefined

The thing is, that watches field is untyped so we won't see type "state" in AST and the functions sheriff_$_record_$_state would be not generated. This is what produced by compiler for watch and state:

<pre>
 {attribute,6,record,{watch,[{record_field,7,{atom,7,filename}}]}},
 {attribute,6,type,
     {{record,watch},
      [{typed_record_field,
           {record_field,7,{atom,7,filename}},
           {type,7,union,[{atom,7,undefined},{type,7,string,[]}]}}],
      []}},

 {attribute,10,type,{iwatch,{type,10,record,[{atom,10,watch}]},[]}},
 {attribute,12,record,{state,[{record_field,13,{atom,13,watches}}]}},
 {attribute,16,type,{istate,{type,16,record,[{atom,16,state}]},[]}},
</pre>

**Comment by essen** [comment]
OK I'll fix it. Thanks for the report!

Sorry I didn't see this earlier, seems I have email troubles with most of the repositories. Will be fixed.

**Comment by essen** [comment]
It looks like there's more issues with records than just this. I'll need to add tests for them.

**Comment by essen** [comment]
Fixed in 166f28a1eac2bdf557c4d073f39038c7cb587477. Thanks! And sorry for the long wait.

**Comment by define-null** [comment]
Thank you)
