### ISSUE TITLE
"Warning: variable 'Sheriff_check_value' is unused"

### ISSUE THREAD

**Issue by yfyf** [extend/sheriff#21]
This isn't a bug, but just an annoying compilation warning that I am getting, thought it might be interesting for you:

The project is here: https://github.com/yfyf/perforator

```
==> perforator (compile)
Compiled src/perforator_utils.erl
/home/yfyf/sandbox/perforator/src/perforator_types.erl:0: Warning: variable 'She
riff_check_value' is unused
/home/yfyf/sandbox/perforator/src/perforator_types.erl:0: Warning: variable 'She
riff_check_value' is unused
/home/yfyf/sandbox/perforator/src/perforator_types.erl:0: Warning: variable 'She
riff_check_value' is unused
Compiled src/perforator_types.erl
```

**Comment by essen** [comment]
Fixed in 9f8c115ba41a7fb01f0b307ff8fb62b61f927e84. Thanks!

**Comment by essen** [comment]
Hope you'll continue working on your project by the way. I find it very interesting.

**Comment by yfyf** [comment]
Thanks for the fix and for the motivation. Unfortunately, lately I'm (and the rest of the team) are pretty much overloaded with lots of other work. My hope is that somehow a proper business use case pops up for this and then I can get an opportunity to do it as part of my daily work for at least some time. Or otherwise there's hope to hack on it a bit during holidays :-)
