### ISSUE TITLE
Opaque types leads to runtime error

### ISSUE THREAD

**Issue by define-null** [extend/sheriff#22]
If opaque_type is used inside other type which will be checked with sheriff, {undef,[{MODULE,'sheriff_$_type_$_OPAQUE_TYPE will occure on runtime checking. I suppose compilation should fail in this case)

**Comment by essen** [comment]
Interesting. Will look, thanks!

**Comment by essen** [comment]
It looks like I cannot do anything.

When declaring types, I get a different AST for -opaque and -type, so far so good.

When going recursively through a type like a tuple or a record, I only have the name of the type. I could always check if the type is opaque if the types are all local, but I wouldn't be able to if the type is exported (like `cowboy_req:req()`). As such there is no good solution for this.

I will add a note in the documentation instead. Done in 8d69829a488d17962a9719448f6609cc8c6a39e7.

Thanks!
